### ISSUE TITLE
Create design of app

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/sbt#8]
We have created a mockup of the first section of this app. What are your thoughts, feelings, opinions, @ruthgrindley?

**Comment by maxgerber** [comment]
https://www.figma.com/file/LE0QcWB8z8TOaefabGEykZAZ/Scottish-Book-Trust

**Comment by ruthgrindley** [comment]
Morning guys. I think it looks great. I love the simplicity. It does remind me of our older branding however, wondering if we could use our brand fonts, colour palette. http://www.scottishbooktrust.com/bookbug/working-with-bookbug/running-your-local-bookbug-programme/logos-images-and-branding
I also wonder whether we need to come up with a title, or action to clarify the point of the app? like a hashtag, #lovelibraries? or #morethanbooks, than shows as a title on each page?

**Comment by rebecacalvoquintero** [comment]
Hi @ruthgrindley! We definitely can incorporate the logo in the website! And we agree, we should include something to clarify the purpose of the app. We will be  in your office around midday, it would be great if we could catch up then! :)

**Comment by ruthgrindley** [comment]
Great! I'm here until 3.40ish (another meeting!)

**Comment by rebecacalvoquintero** [comment]
@ruthgrindley Amazing! we will see you then! Also Ruth, we can see the logo but we can't see your colour palette. Do you have any other link where we can find your colour palette?

Thanks a lot!

**Comment by ruthgrindley** [comment]
Hi, it's page 19 of the branding doc.
http://www.scottishbooktrust.com/files/sbt_and_bookbug_logo_guidelines.pdf
I'm also looking out a better Bookbug logo for use to use on the second screen for the Bookbug Session option. I need to edit on illustrator but I'll get it to you soon!

**Comment by ruthgrindley** [comment]
![bookbug stamp 15mm diameter aw](https://user-images.githubusercontent.com/33876488/33169823-edd29f80-d03d-11e7-9cfc-3483c2b5b784.jpg)

**Comment by ruthgrindley** [comment]
Full branding guidelines...
[SBT-01-Brand-Guidelines-FULL.pdf](https://github.com/InFact-coop/sbt/files/1499219/SBT-01-Brand-Guidelines-FULL.pdf)

**Comment by ruthgrindley** [comment]
![blue and blue background](https://user-images.githubusercontent.com/33876488/33174751-3e01be56-d051-11e7-9511-bbc8592bb52e.jpg)
![green with green tint](https://user-images.githubusercontent.com/33876488/33174752-3e14d842-d051-11e7-9be9-99be7b364fa5.jpg)
![orange and orange tint](https://user-images.githubusercontent.com/33876488/33174753-3e27fe2c-d051-11e7-95c2-3be1f5914e35.jpg)
![pink and pink tint](https://user-images.githubusercontent.com/33876488/33174754-3e3d2b30-d051-11e7-9eeb-729cf23f2898.jpg)
![red with red tint](https://user-images.githubusercontent.com/33876488/33174755-3e50e742-d051-11e7-9bcc-5fed7fd3c668.jpg)
![yellow with yellow tint](https://user-images.githubusercontent.com/33876488/33174756-3e637aa6-d051-11e7-875c-40e24d987a30.jpg)
Flicks...

**Comment by ruthgrindley** [comment]
So, this platform doesn't support txt. files, shall I email them over?

**Comment by ruthgrindley** [comment]
Typography info is in the full brand guidelines from p.15 onwards... We only have one serif font which is only really supposed to be used for large blocks of text. Altis Book is to be used for headings and helvetica for secondary type.

**Comment by ruthgrindley** [comment]
If you give me an email I can send them over.

R

**Comment by rebecacalvoquintero** [comment]
@ruthgrindley rebecacalvoquintero@hotmail.es; mgerber94@gmail.com;

**Comment by ruthgrindley** [comment]
Read or Dead? too much? ;)

**Comment by rebecacalvoquintero** [comment]
Hi @ruthgrindley. Would you know at what time would be the presentation? Also, unfortunately, we could not implement the feature of different quotes but for the build sprint we will for sure!

**Comment by ruthgrindley** [comment]
Hi @rebecacalvoquintero @maxgerber. I hope you guys are well and had a safe journey down to London. I checked in with Marc and he wasn't aware of a presentation today. He also isn't in so was wondering if we could reschedule? I've given them a brief update of the project. I will make sure a we set a date for the presentation soon, and will let you know ASAP.

**Comment by rebecacalvoquintero** [comment]
Hi @ruthgrindley. We are trying to figure out when it would be best to do this and we will come back to you asap. Thanks a lot!

**Comment by ruthgrindley** [comment]
Thanks @rebecacalvoquintero This week is crazy due to Book Week Scotland, literally our busiest week of the year! Not the best sprint planning on Marc's part. Let me know your available dates and I'll sort something.

Ruth :)

**Comment by rebecacalvoquintero** [comment]
@maxgerber @ruthgrindley Hello Ruth! We could not do tomorrow. But what about on Wednesday or Thursday from 14 h on?

**Comment by ruthgrindley** [comment]
Sorry @maxgerber @rebecacalvoquintero  I think this week is out for us because of Book Week Scotland, a lot of staff are out the office, including senior management.

How are you fixed for next week?

R

**Comment by rebecacalvoquintero** [comment]
@ruthgrindley we would need to check tomorrow as we will be working with another charity. But we will let you know tomorrow. Thank you!

**Comment by ruthgrindley** [comment]
@maxgerber @rebecacalvoquintero No problem, sorry for the hassle.

**Comment by rebecacalvoquintero** [comment]
@ruthgrindley hello Ruth! how are you? when would it be good for you, Mark and the rest of the people that would like to see the presentation to arrange the presentation?

**Comment by ruthgrindley** [comment]
Hi @rebecacalvoquintero Sorry for the delay. I was off at the end of last week. We have a meeting with our Digital Board tomorrow, I'll check with them for a date that's suitable. Are there any times/days I should avoid? What is your availability like? We could maybe catch up over the phone some time soon to plan the presentation, it would be good to get your steer on it.

**Comment by maxgerber** [comment]
Hi @ruthgrindley no worries, I'm sure book week was insanely busy, hope you had a chance to rest. That'd be great - the 8th, 12th, and 14th of December would work great for us. Could you float that to the Digital Board and see if that works for you guys? Those dates would also work for us if you felt like having a google hangouts call or something beforehand :)
Have you had a chance to have a look at the [final product?](https://sbt.surge.sh)
Would be great to hear your initial thoughts
